### ISSUE TITLE
[ Site | Done ] Update CNAME to avoid redirect.

### ISSUE THREAD

**Issue by francismakes** [francismakes/sd-roasters#8]
[localsandiego.coffee](http://localsandiego.coffee) was bought today. Go update it.

**Comment by francismakes** [comment]
https://help.github.com/articles/adding-a-cname-file-to-your-repository/

**Comment by francismakes** [comment]
# Setup: Github Pages x Google Domains

1. Set your repository's default branch to `gh-pages`.
2. Create and commit a CNAME file.
3. Configure the DNS settings.


### [1] gh-pages (Github)
Since this is a [Project page](https://pages.github.com/#vanilla-step-1), set the default branch to `gh-pages`. 
![repo-settings](https://cloud.githubusercontent.com/assets/2647488/6539421/a828f1d8-c428-11e4-8665-e51d06fcfd2e.png)

### [2] CNAME (Github)
Create and commit a [CNAME file](https://github.com/francismakes/sd-roasters/blob/gh-pages/CNAME)  to `gh-pages`. There can [only be one name](https://help.github.com/articles/adding-a-cname-file-to-your-repository/) in the CNAME file.

### [3] Configure DNS (Google Domains)
Within the [Google Domains](https://domains.google.com/registrar) Settings, navigate to `Configure DNS`. There is a bottom section entitled `Custom Resource Records` Place the following configuration.

| Name | Type | TTL | Data
----------|---------|--------|---------|
@ | A | 1h | 192.30.252.153
 | | | 192.30.252.154 
www | CNAME | 1h | localsandiego.coffee

#### Notes 
* As of this writing, `192.30.252.153` and `192.30.252.154` are [the current IPv4 addresses that Github uses](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/) for the A Records (thanks to @WarriorIng64 for his [relevant blog post](http://blog.christopherkylehorton.com/2015/01/setting-up-my-custom-domain-with-github.html)).
* After completing the input, there is an automatically appended period to to the end of the domain. I don't know why this is.

![googlesettings](https://cloud.githubusercontent.com/assets/2647488/6539423/ac85233c-c428-11e4-8d82-1322423b27ec.png)


## [localsandiego.coffee](http://localsandiego.coffee)
Look ma, no redirects!

**Comment by WarriorIng64** [comment]
Thank you for the reference to my blog post! I'm glad it helped someone. :smile:
